#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_GAME_TIMER_PERIOD 40.0E-3f

// SPEED OF PLAYER (pixels/sec)
#define CONFIG_PLAYER_DISTANCE_PER_SECOND 150
#define CONFIG_PLAYER_DISTANCE_PER_TICK (CONFIG_PLAYER_DISTANCE_PER_SECOND * CONFIG_GAME_TIMER_PERIOD)

#define CONFIG_TEXT_H 16
//Dimensions of platforms
#define CONFIG_GROUND_Y (LCD_H - 16)
#define CONFIG_PLATFORM_H 16
#define CONFIG_PLATFORM_W LCD_W * ((float)3/4)
#define CONFIG_PLATFORM_W_2 (LCD_W)
#define CONFIG_PLATFORM_X_LEFT 0
#define CONFIG_PLATFORM_X_RIGHT 48
#define CONFIG_PLATFORM_Y_1 144
#define CONFIG_PLATFORM_Y_2 64
#define CONFIG_BOX_X (LCD_W  - 48)
#define CONFIG_BOX_Y (LCD_H -  48)
#define CONFIG_BOX_W 48
#define CONFIG_BOX_H 32

//COnstants for obstacles
#define CONFIG_FIRE_X1 60
#define CONFIG_FIRE_X2 65
#define CONFIG_FIRE_X3 70
#define CONFIG_FIRE_Y1 (LCD_H - 16)
#define CONFIG_FIRE_Y2 (LCD_H - 32)
#define CONFIG_FIRE_Y3 (LCD_H - 16)
#define CONFIG_WATER_X1 160
#define CONFIG_WATER_X2 165
#define CONFIG_WATER_X3 170
#define CONFIG_WATER_Y1 (LCD_H - 16)
#define CONFIG_WATER_Y2 (LCD_H - 32)
#define CONFIG_WATER_Y3 (LCD_H - 16)
#define CONFIG_GOO_X1 160
#define CONFIG_GOO_X2 165
#define CONFIG_GOO_X3 170
#define CONFIG_GOO_Y1 144
#define CONFIG_GOO_Y2 128
#define CONFIG_GOO_Y3 144

#define CONFIG_TRIANGLE_OFFSET_1 10

#define CONFIG_TRIANGLE_OFFSET_2 20



//Constants for Button and LEver
#define CONFIG_BUTTON1_X 80
#define CONFIG_BUTTON1_Y 49
#define CONFIG_BUTTON2_X 215
#define CONFIG_BUTTON2_Y 49
#define CONFIG_LEVER_X 75
#define CONFIG_LEVER_Y 129

//Final postion constants
#define CONFIG_FINAL_DOOR_X_FIRE 250
#define CONFIG_FINAL_DOOR_Y_FIRE 8
#define CONFIG_FINAL_DOOR_X_WATER (LCD_W - CONFIG_FINAL_DOOR_W)
#define CONFIG_FINAL_DOOR_Y_WATER 8
#define CONFIG_FINAL_DOOR_W 32
#define CONFIG_FINAL_DOOR_H 56

//Boundaries
#define CONFIG_LEFT_WALL 0
#define CONFIG_RIGHT_WALL (LCD_W - 32)

//Elevator COnstants
#define CONFIG_ELEV_H 16
#define CONFIG_ELEV_W 48
#define CONFIG_ELEV_SPEED_PER_SEC 10
#define CONFIG_ELEV_SPEED_PER_TICK (CONFIG_ELEV_SPEED_PER_SEC * CONFIG_GAME_TIMER_PERIOD)


// Player size
#define CONFIG_PLAYER_WIDTH  32
#define CONFIG_PLAYER_HEIGHT 32


// Colors
#define CONFIG_COLOR_BACKGROUND rgb565(128, 128, 128)
#define CONFIG_GAME_OVER_COLOR BLACK


#define CONFIG_TITLE_COLOR GREEN

#define CONFIG_COLOR_CURSOR WHITE
#define CONFIG_COLOR_STATUS WHITE

#define CONFIG_COLOR_FIRE RED
#define CONFIG_COLOR_GOO GREEN
#define CONFIG_COLOR_WATER  BLUE
#define CONFIG_COLOR_ELEVATOR rgb565(230, 175, 6)
#define CONFIG_COLOR_DOOR PURPLE
#define CONFIG_COLOR_PLATFORM rgb565(111, 78, 55)

#endif // CONFIG_H
